// frontend-react/src/components/PM8000Card.tsx
import { useState, useEffect } from 'react'
import { Card } from './ui/card'
import { Badge } from './ui/badge'
import HalfGauge from './HalfGauge'
import type { Meter } from '../types'
import { Zap, CheckCircle, PowerOff } from 'lucide-react'

function loadMeterZones(meterName: string, fallback: any) {
  try {
    const stored = localStorage.getItem('scada_meter_zones')
    if (!stored) return fallback
    const all = JSON.parse(stored)
    return all[meterName] ?? fallback
  } catch { return fallback }
}

export default function PM8000Card({ m }: { m: Meter }) {
  const fallback = m.uiConfig?.zones ?? {}
  const [zones, setZones] = useState(() => loadMeterZones(m.name, fallback))

  useEffect(() => {
    const handler = () => setZones(loadMeterZones(m.name, fallback))
    window.addEventListener('meterZonesUpdated', handler)
    return () => window.removeEventListener('meterZonesUpdated', handler)
  }, [])

  const title = m.uiConfig?.title || m.name

  const v = zones.voltage || { min: 0, max: 36, redLow: 30, green: 33, yellow: 34.5 }
  const i = zones.current || { min: 0, max: 200, green: 120, yellow: 170 }
  const p = zones.power   || { min: 0, max: 2000, green: 1500, yellow: 1800 }
  const f = zones.pf      || { min: 0, max: 1, green: 0.85, yellow: 0.95 }

  const gauges = [
    { value: (m.voltage || 0) / 1000, label: 'Tensión L-L', unit: 'kV', ...v, decimals: 2 },
    { value: m.current || 0,          label: 'Corriente',   unit: 'A',  ...i },
    { value: (m.power || 0) / 1000,   label: 'Potencia',    unit: 'kW', ...p },
    { value: Math.abs(m.pf || 0),     label: 'Factor Pot.', unit: '',   ...f, decimals: 3, invert: true }
  ]

  return (
    <Card className="border-l-4" style={{ borderLeftColor: m.online ? '#16a34a' : '#9ca3af' }}>
      <div className="flex items-center justify-between p-4 pb-2">
        <div className="flex items-center gap-2">
          <Zap className="h-5 w-5 text-primary" />
          <span className="font-bold text-base">{title}</span>
          <Badge variant="secondary">PM8000</Badge>
        </div>
        {m.online ? (
          <Badge variant="success" className="gap-1 px-3 py-1 text-xs font-bold">
            <CheckCircle className="h-3 w-3" /> ONLINE
          </Badge>
        ) : (
          <Badge variant="secondary" className="gap-1 px-3 py-1 text-xs font-bold">
            <PowerOff className="h-3 w-3" /> OFFLINE
          </Badge>
        )}
      </div>
      <div className="border-b" />
      {m.online ? (
        <div className="grid grid-cols-4 gap-2 p-4">
          {gauges.map((g) => <HalfGauge key={g.label} {...g} />)}
        </div>
      ) : (
        <div className="text-center py-8 text-muted-foreground">
          <PowerOff className="h-9 w-9 mx-auto mb-1 opacity-50" />
          <div className="text-sm">Medidor sin conexión</div>
        </div>
      )}
    </Card>
  )
}

// frontend/src/components/PM8000Card.vue
<template>
  <v-card :style="{ borderLeft: `4px solid ${m.online ? '#16a34a' : '#9ca3af'}` }"
          elevation="2" rounded="lg" class="pa-0">
    <v-card-item class="pb-1">
      <template #title>
        <div class="d-flex align-center" style="gap:8px">
          <v-icon color="indigo">mdi-flash</v-icon>
          <span class="font-weight-bold" style="font-size:1.1em">{{ title }}</span>
          <v-chip size="x-small" variant="tonal" color="indigo">PM8000</v-chip>
        </div>
      </template>
      <template #append>
        <v-chip :color="m.online ? 'green' : 'grey'" variant="elevated" size="default" label
                style="font-weight:800; letter-spacing:0.5px">
          <v-icon start :icon="m.online ? 'mdi-check-circle' : 'mdi-power-plug-off'" />
          {{ m.online ? 'ONLINE' : 'OFFLINE' }}
        </v-chip>
      </template>
    </v-card-item>
    <v-divider />
    <div v-if="m.online" class="gauges-grid">
      <HalfGauge v-for="g in gauges" :key="g.label" v-bind="g" />
    </div>
    <div v-else class="text-center pa-6 text-grey-lighten-1">
      <v-icon size="36" color="grey-lighten-1">mdi-power-plug-off</v-icon>
      <div class="mt-1">Medidor sin conexión</div>
    </div>
  </v-card>
</template>

<script setup>
import { computed } from 'vue'
import HalfGauge from './HalfGauge.vue'

const props = defineProps({ m: { type: Object, required: true } })

const title = computed(() => props.m.uiConfig?.title || 'Medición Línea Exclusiva')

const gauges = computed(() => {
  const m = props.m
  const c = m.uiConfig?.zones || {}
  const v = c.voltage || { min: 0, max: 36, green: 33, yellow: 34.5 }
  const i = c.current || { min: 0, max: 200, green: 120, yellow: 170 }
  const p = c.power   || { min: 0, max: 2000, green: 1500, yellow: 1800 }
  const f = c.pf      || { min: 0, max: 1, green: 0.85, yellow: 0.95 }
  return [
    { value: (m.voltage || 0) / 1000, label: 'Tensión L-L', unit: 'kV', ...v, decimals: 2 },
    { value: m.current || 0,          label: 'Corriente',   unit: 'A',  ...i },
    { value: (m.power || 0) / 1000,   label: 'Potencia',    unit: 'kW', ...p },
    { value: Math.abs(m.pf || 0),     label: 'Factor Pot.', unit: '',   ...f, decimals: 3, invert: true }
  ]
})
</script>

<style scoped>
.gauges-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 8px;
  padding: 12px 16px;
}
</style>
